/*
 * generated by Xtext 2.38.0
 */
package org.xtext.example.mdsd;


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
public class MathStandaloneSetup extends MathStandaloneSetupGenerated {

	public static void doSetup() {
		new MathStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}
