/*
 * generated by Xtext 2.38.0
 */
package org.xtext.example.mdsd.ui.tests;

import com.google.inject.Injector;
import org.eclipse.xtext.testing.IInjectorProvider;
import org.xtext.example.mdsd.ui.internal.MdsdActivator;

public class MathUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return MdsdActivator.getInstance().getInjector("org.xtext.example.mdsd.Math");
	}

}
