/**
 * generated by Xtext 2.38.0
 */
package org.xtext.example.mdsd.math;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Expression</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see org.xtext.example.mdsd.math.MathPackage#getExpression()
 * @model
 * @generated
 */
public interface Expression extends EObject
{
} // Expression
