/**
 * generated by Xtext 2.38.0
 */
package org.xtext.example.mdsd.math;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>External Decl</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mdsd.math.ExternalDecl#getName <em>Name</em>}</li>
 *   <li>{@link org.xtext.example.mdsd.math.ExternalDecl#getParameters <em>Parameters</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.mdsd.math.MathPackage#getExternalDecl()
 * @model
 * @generated
 */
public interface ExternalDecl extends EObject
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see org.xtext.example.mdsd.math.MathPackage#getExternalDecl_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link org.xtext.example.mdsd.math.ExternalDecl#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Parameters</b></em>' attribute list.
   * The list contents are of type {@link java.lang.String}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Parameters</em>' attribute list.
   * @see org.xtext.example.mdsd.math.MathPackage#getExternalDecl_Parameters()
   * @model unique="false"
   * @generated
   */
  EList<String> getParameters();

} // ExternalDecl
