/**
 * generated by Xtext 2.38.0
 */
package org.xtext.example.mdsd.math;

import org.eclipse.emf.common.util.EList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Function Call</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mdsd.math.FunctionCall#getName <em>Name</em>}</li>
 *   <li>{@link org.xtext.example.mdsd.math.FunctionCall#getArguments <em>Arguments</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.mdsd.math.MathPackage#getFunctionCall()
 * @model
 * @generated
 */
public interface FunctionCall extends Expression
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' reference.
   * @see #setName(ExternalDecl)
   * @see org.xtext.example.mdsd.math.MathPackage#getFunctionCall_Name()
   * @model
   * @generated
   */
  ExternalDecl getName();

  /**
   * Sets the value of the '{@link org.xtext.example.mdsd.math.FunctionCall#getName <em>Name</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' reference.
   * @see #getName()
   * @generated
   */
  void setName(ExternalDecl value);

  /**
   * Returns the value of the '<em><b>Arguments</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.example.mdsd.math.Expression}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Arguments</em>' containment reference list.
   * @see org.xtext.example.mdsd.math.MathPackage#getFunctionCall_Arguments()
   * @model containment="true"
   * @generated
   */
  EList<Expression> getArguments();

} // FunctionCall
