/*
 * generated by Xtext 2.38.0
 */
package org.xtext.example.mdsd.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
public class MathUiModule extends AbstractMathUiModule {

	public MathUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
