/*
 * generated by Xtext 2.38.0
 */
package org.xtext.example.mdsd.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractMathScopeProvider extends DelegatingScopeProvider {
}
