/*
 * generated by Xtext 2.38.0
 */
package dk.sdu.mmmi.mdsd;


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class MathRuntimeModule extends AbstractMathRuntimeModule {
}
