/**
 * generated by Xtext 2.38.0
 */
package dk.sdu.mmmi.mdsd.math;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Exp</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link dk.sdu.mmmi.mdsd.math.Exp#getAssignments <em>Assignments</em>}</li>
 *   <li>{@link dk.sdu.mmmi.mdsd.math.Exp#getBody <em>Body</em>}</li>
 * </ul>
 *
 * @see dk.sdu.mmmi.mdsd.math.MathPackage#getExp()
 * @model
 * @generated
 */
public interface Exp extends EObject
{
  /**
   * Returns the value of the '<em><b>Assignments</b></em>' containment reference list.
   * The list contents are of type {@link dk.sdu.mmmi.mdsd.math.VariableAssignment}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Assignments</em>' containment reference list.
   * @see dk.sdu.mmmi.mdsd.math.MathPackage#getExp_Assignments()
   * @model containment="true"
   * @generated
   */
  EList<VariableAssignment> getAssignments();

  /**
   * Returns the value of the '<em><b>Body</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Body</em>' containment reference.
   * @see #setBody(Exp)
   * @see dk.sdu.mmmi.mdsd.math.MathPackage#getExp_Body()
   * @model containment="true"
   * @generated
   */
  Exp getBody();

  /**
   * Sets the value of the '{@link dk.sdu.mmmi.mdsd.math.Exp#getBody <em>Body</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Body</em>' containment reference.
   * @see #getBody()
   * @generated
   */
  void setBody(Exp value);

} // Exp
