/**
 * generated by Xtext 2.38.0
 */
package dk.sdu.mmmi.mdsd.math;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Let Expression</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link dk.sdu.mmmi.mdsd.math.LetExpression#getName <em>Name</em>}</li>
 *   <li>{@link dk.sdu.mmmi.mdsd.math.LetExpression#getValue <em>Value</em>}</li>
 *   <li>{@link dk.sdu.mmmi.mdsd.math.LetExpression#getBody <em>Body</em>}</li>
 * </ul>
 *
 * @see dk.sdu.mmmi.mdsd.math.MathPackage#getLetExpression()
 * @model
 * @generated
 */
public interface LetExpression extends Exp
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see dk.sdu.mmmi.mdsd.math.MathPackage#getLetExpression_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link dk.sdu.mmmi.mdsd.math.LetExpression#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Value</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Value</em>' containment reference.
   * @see #setValue(Exp)
   * @see dk.sdu.mmmi.mdsd.math.MathPackage#getLetExpression_Value()
   * @model containment="true"
   * @generated
   */
  Exp getValue();

  /**
   * Sets the value of the '{@link dk.sdu.mmmi.mdsd.math.LetExpression#getValue <em>Value</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Value</em>' containment reference.
   * @see #getValue()
   * @generated
   */
  void setValue(Exp value);

  /**
   * Returns the value of the '<em><b>Body</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Body</em>' containment reference.
   * @see #setBody(Exp)
   * @see dk.sdu.mmmi.mdsd.math.MathPackage#getLetExpression_Body()
   * @model containment="true"
   * @generated
   */
  Exp getBody();

  /**
   * Sets the value of the '{@link dk.sdu.mmmi.mdsd.math.LetExpression#getBody <em>Body</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Body</em>' containment reference.
   * @see #getBody()
   * @generated
   */
  void setBody(Exp value);

} // LetExpression
